[package]
name = "greeting_bot"
version = "0.1.0"
authors = ["dmitri9149"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
regex = "1"
